import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from '@/context/ThemeContext'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ichwanul Muslim - Portfolio Website",
  description: "My Portfolio Website - Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className="bg-white dark:bg-[#161616] text-[#363632] dark:text-[#9a9a89] transition-colors relative"> 
          {children}
        </body>
      </ThemeProvider>     
    </html>
  );
}
